pipeline {
    agent any

    tools {
        maven 'Maven'
    }

    environment {
        APP_NAME  = 'transaction-service'
        IMAGE_NAME = "securefinops/${APP_NAME}"
        IMAGE_TAG  = "${BUILD_NUMBER}"
        GIT_COMMIT = "${GIT_COMMIT}"
        GIT_BRANCH = "${GIT_BRANCH}"
    }

    stages {

        stage('Checkout') {
            steps {
                checkout scm
                echo "Checked out branch: ${env.BRANCH_NAME}"
            }
        }

        stage('Build JAR') {
            steps {
                sh 'mvn clean package -DskipTests'
            }
        }

        stage('Unit Tests') {
            steps {
                   withCredentials([
                    string(credentialsId: 'DB_USER', variable: 'DB_USER'),
                    string(credentialsId: 'DB_PASSWORD', variable: 'DB_PASSWORD')
                ]) {
                    sh '''
                        mvn test \
                            -Dspring.datasource.url=jdbc:postgresql://securefinops-postgres-local:5432/transactiondb \
                            -Dspring.datasource.username=${DB_USER} \
                            -Dspring.datasource.password=${DB_PASSWORD}
                    '''
                }
            }
            post {
                always {
                    junit '**/target/surefire-reports/*.xml'
                }
            }
        }

        stage('Pull Security Images') {
            steps {
                sh '''
                    docker pull semgrep/semgrep:latest
                    docker pull aquasec/trivy:latest
                '''
            }
        }

        stage('SAST - Semgrep') {
            steps {
                sh '''
                    docker run --rm \
                        -v ${WORKSPACE}:/src \
                        semgrep/semgrep:latest \
                        semgrep scan \
                            --config p/java \
                            --config p/owasp-top-ten \
                            --config p/secrets \
                            --json \
                            --output /src/semgrep-results.json \
                            /src || true
                '''
            }
        }

        stage('SCA - Trivy Filesystem') {
            steps {
                sh '''
                    docker run --rm \
                        -v ${WORKSPACE}:/src \
                        aquasec/trivy:latest \
                        fs \
                            --format json \
                            --output /src/trivy-fs-results.json \
                            --severity HIGH,CRITICAL \
                            /src || true
                '''
            }
        }

        stage('Build Docker Image') {
            steps {
                sh """
                    docker build \
                        -t ${IMAGE_NAME}:${IMAGE_TAG} \
                        -t ${IMAGE_NAME}:latest \
                        .
                """
            }
        }

        stage('Image Scan - Trivy') {
            steps {
                sh """
                    docker run --rm \
                        -v /var/run/docker.sock:/var/run/docker.sock \
                        -v ${WORKSPACE}:/src \
                        -v trivy-cache:/root/.cache/trivy \
                        aquasec/trivy:latest \
                        image \
                            --format json \
                            --output /src/trivy-image-results.json \
                            --severity HIGH,CRITICAL \
                            --exit-code 0 \
                            ${IMAGE_NAME}:${IMAGE_TAG}
                """
            }
            post {
                always {
                    archiveArtifacts artifacts: 'trivy-image-results.json',
                                    allowEmptyArchive: true
                }
            }
        }

        stage('Deploy Staging') {
            steps {
                withCredentials([
                    string(credentialsId: 'DB_USER', variable: 'DB_USER'),
                    string(credentialsId: 'DB_PASSWORD', variable: 'DB_PASSWORD')
                ]) { 
                    sh """
                        docker stop ${APP_NAME}-staging || true
                        docker rm ${APP_NAME}-staging || true
                        docker run -d \
                            --name ${APP_NAME}-staging \
                            --network securefinops-network \
                            -p 8082:8080 \
                            -e DB_USER=${DB_USER} \
                            -e DB_PASSWORD=${DB_PASSWORD} \
                            -e SPRING_DATASOURCE_URL=jdbc:postgresql://securefinops-postgres-local:5432/transactiondb \
                            ${IMAGE_NAME}:${IMAGE_TAG}
                    """
                }
            }
        }

        stage('Health Check - staging') {
            steps {
                sleep(20)
                sh '''
                    curl -f http://transaction-service-staging:8080/actuator/health || \
                    (echo "Health check failed" && exit 1)
                '''
            }
        }
    }

    post {
        success {
            echo """ Pipeline SUCCESS:
                IMAGE_NAME --- ${IMAGE_NAME}
                Build -------- ${BUILD_NUMBER}
                Commit ------- ${GIT_COMMIT}
                Branch ------- ${GIT_BRANCH}
            """
        }
        failure {
            echo """ Pipeline FAILED:
                IMAGE_NAME --- ${IMAGE_NAME}
                Build -------- ${BUILD_NUMBER}
                Commit ------- ${GIT_COMMIT}
                Branch ------- ${GIT_BRANCH}
            """
        }
        always {
            cleanWs()
        }
    }
}